#!/usr/bin/env ruby
# frozen_string_literal: true

require "manageiq-floe"
require "optimist"

opts = Optimist.options do
  version "v#{ManageIQ::Floe::VERSION}\n"
  opt :workflow, "Path to your workflow json", :type => :string, :required => true
  opt :inputs, "JSON payload to input to the workflow", :type => :string, :default => '{}'
end

require "logger"
ManageIQ::Floe.logger = Logger.new(STDOUT)

ManageIQ::Floe::Workflow.load(opts[:workflow], "global" => opts[:inputs]).run!
